openapi: 3.0.0
info:
  title: Jitterbit Order Manager API
  version: 1.0.0
  description: API para gerenciamento de pedidos.

servers:
  - url: http://localhost:3000

paths:
  /order:
    post:
      summary: Criar novo pedido
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
      responses:
        '201':
          description: Pedido criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /order/list:
    get:
      summary: Listar todos os pedidos
      tags: [Orders]
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /order/{id}:
    get:
      summary: Buscar pedido pelo ID
      tags: [Orders]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID interno do MongoDB
      responses:
        '200':
          description: Pedido encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Pedido não encontrado

    put:
      summary: Atualizar um pedido pelo ID
      tags: [Orders]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdate'
      responses:
        '200':
          description: Pedido atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

    delete:
      summary: Deletar um pedido pelo ID
      tags: [Orders]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pedido deletado
        '404':
          description: Pedido não encontrado

components:
  schemas:

    Item:
      type: object
      properties:
        idItem:
          type: string
          example: "5678"
        quantidadeItem:
          type: number
          example: 2
        valorItem:
          type: number
          example: 2750

    OrderCreate:
      type: object
      required:
        - numeroPedido
        - valorTotal
        - items
      properties:
        numeroPedido:
          type: string
          example: "v10089016vdb-02"
        valorTotal:
          type: number
          example: 5500
        status:
          type: string
          example: "processando"
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'

    OrderUpdate:
      type: object
      properties:
        numeroPedido:
          type: string
        valorTotal:
          type: number
        status:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'

    Order:
      type: object
      properties:
        _id:
          type: string
          example: "64dab8a0f6b7183237d307f6"
        numeroPedido:
          type: string
          example: "v10089016vdb-02"
        valorTotal:
          type: number
          example: 5500
        dataCriacao:
          type: string
          format: date-time
          example: "2025-12-01T16:32:53.681Z"
        status:
          type: string
          example: "pago"
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        __v:
          type: number
          example: 0
